# Generated by Django 2.1.7 on 2019-03-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='abv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
