# Generated by Django 2.1.7 on 2019-03-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_auto_20190326_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
